# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.8
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
  - id: black
    args: [--line-length, '79']
- repo: https://github.com/PyCQA/pylint
  rev: v2.15.9
  hooks:
  - id: pylint
    args: [--ignore, localtypes.py]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
